In [5]:
import numpy as np

#### 1) Create a vector of size 15 having third element (i.e. position 2) set to 1 and rest of the elements should be zero. 

In [25]:
v = np.array([0,0,1,0,0,0,0,0,0,0,0,0,0,0,0])
v

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 2) Create a vector with values ranging from 21 to 30

In [24]:
v2 = np.arange(21,31)
v2

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

#### 3) Reverse the order of elements in the vector in question 2. That is, the previous last element should be the first one now. 

In [43]:
v2_rev = np.flip(v2)
v2_rev

array([30, 29, 28, 27, 26, 25, 24, 23, 22, 21])

#### 4) Define a vector with values ranging from 1 to 12. Now define a 4x3 matrix to store elements from the vector you have defined. That is, first 3 elements of the vector should be row 1 of the matrix, next 3 should be row 2, and so on. 

In [44]:
v3 = np.arange(1,13)
m = v3.reshape(4,3)
m

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### 5) Consider the 4x3 matrix from question 4. Add 100 to all values that are greater than equal to 3 and less than equal to 8

In [57]:
m[np.logical_and((m >=3), (m<=8))] +=100
print(m)

[[  1   2 103]
 [104 105 106]
 [107 108   9]
 [ 10  11  12]]


#### 6) Consider the vector x = [1, 0, 6, 9, 10, 0]. Print the indices of non-zero elements. 

In [55]:
x = np.array([1, 0, 6, 9, 10, 0])
print(x[x!= 0])

[ 1  6  9 10]


#### 7) Define a 6x3 matrix with random values. Normalize this matrix by subtracting the mean (of the column) and dividing by the standard deviation (of the column). 

In [68]:
#define matrix, mean and standard deviation
r = np.random.random((6,3))
mn = r.mean(axis = 0)
sd = r.std(axis = 0)

#subtract mean
r2=np.subtract(r, mn)

#divide by std dev
r3 = np.divide(r2, sd) 
print(r3)


[[-0.42475358 -1.60456057  1.57437685]
 [ 0.02848694 -1.11027852  0.57325796]
 [-0.06745862  0.51422024  0.46944887]
 [-1.79417122  0.27623382 -0.30404653]
 [ 0.97708713  0.9746526  -1.47653098]
 [ 1.28080935  0.94973244 -0.83650618]]


#### 8) Define a 3x4 matrix with random values. Define a 4x3 matrix with random values. Multiply the two matrices. 

In [69]:
a = np.random.random((3,4))
b = np.random.random((4,3))
print(np.dot(a,b))

[[1.70014698 0.36206776 1.5004683 ]
 [1.69020081 0.60152737 1.85263042]
 [1.79897238 0.62003211 1.88875628]]


#### 9) Define a 3x3 identity matrix.

In [70]:
i = np.eye(3,3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 10) Define a 3x3 matrix A with random values. Invert the matrix A, let’s call this B. Multiply matrices A and B.

In [74]:
A=np.random.random((3,3))
print(A)
B=np.linalg.inv(A)
print(B)

C =np.dot(A,B)
print(C)


[[0.90509991 0.96012887 0.2078148 ]
 [0.22606848 0.30376816 0.44136217]
 [0.54141262 0.12559956 0.58776245]]
[[ 0.66544102 -2.90928291  1.94935713]
 [ 0.57342016  2.26736887 -1.90535486]
 [-0.73550035  2.19534604  0.31289031]]
[[ 1.00000000e+00  1.66533454e-16 -6.93889390e-17]
 [-5.55111512e-17  1.00000000e+00 -2.77555756e-17]
 [-5.55111512e-17  2.22044605e-16  1.00000000e+00]]
